version: "3.0"
services:
        static:
                build: static
                hostname: 'static'
                ports:
                - "80:80"
                restart: 'always'
                depends_on:
                        - readfile
                        - hiddenform
        readfile:
                build: readfile
                hostname: 'readfile'
                restart: 'always'
        hiddenform:
                build: hiddenform
                hostname: 'hiddenform'
                restart: 'always'
        cookiechal:
                build: cookiechal
                hostname: 'cookiechal'
                restart: 'always'
        pingapp:
                build: pingapp
                hostname: 'pingapp'
                restart: 'always'

